### ISSUE TITLE
很认真的提一个Issue 项目名称太长了~

### ISSUE THREAD

**Issue by hyzx86** [52ABP/LTMCompanyNameFree.YoyoCmsTemplate#12]
真的稍微目录深一点就报错了。。
LTM.YoyoCmsTemplate
就好了嘛

**Comment by ltm0203** [comment]
推荐从 ： https://www.52abp.com/Download/Index
下载创建属于您自己的项目。
如果要修改模板页面以及调整模板页面的。给我们贡献代码。可以参考
我的路径信息：
`D:\Source\repos\Github_Code\ltm0203\LTMCompanyNameFree.YoyoCmsTemplate\src\aspnet-core\src\LTMCompanyNameFree.YoyoCmsTemplate.Core\Localization\SourceFiles
`
希望对您有帮助

**Comment by hyzx86** [comment]
@ltm0203 谢谢，开始没搞明白。
