### ISSUE TITLE
An error occurred while starting the application.

### ISSUE THREAD

**Issue by anlew999** [52ABP/LTMCompanyNameFree.YoyoCmsTemplate#13]
An error occurred while starting the application.
SqlException: 列名 'CreatorUserId1' 无效。
列名 'DeleterUserId1' 无效。
列名 'LastModifierUserId1' 无效。
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
===========================================================

>  找到原因了。。EntityFrameworkCore 。DbContext。OnModelCreating必须加base.OnModelCreating(modelBuilder);

===========================================================
VVV.EntityFrameworkCore.Seed.Tenants.DefaultTenantBuilder.CreateDefaultTenant() in DefaultTenantBuilder.cs
+
        

>   ###   **var defaultTenant = _context.Tenants.IgnoreQueryFilters().FirstOrDefault(t => t.TenancyName == AbpTenantBase.DefaultTenantName);**

VVV.EntityFrameworkCore.Seed.Tenants.DefaultTenantBuilder.Create() in DefaultTenantBuilder.cs
+
            CreateDefaultTenant();
VVV.EntityFrameworkCore.Seed.SeedHelper.SeedHostDb(VVVDbContext context) in SeedHelper.cs
+
            new DefaultTenantBuilder(context).Create();
VVV.EntityFrameworkCore.Seed.SeedHelper.WithDbContext<TDbContext>(IIocResolver iocResolver, Action<TDbContext> contextAction) in SeedHelper.cs
+
                    contextAction(context);
VVV.EntityFrameworkCore.Seed.SeedHelper.SeedHostDb(IIocResolver iocResolver) in SeedHelper.cs
+
            WithDbContext<VVVDbContext>(iocResolver, SeedHostDb);
VVV.EntityFrameworkCore.VVVEntityFrameworkModule.PostInitialize() in VVVEntityFrameworkModule.cs
+
                SeedHelper.SeedHostDb(IocManager);
System.Collections.Generic.List<T>.ForEach(Action<T> action)
Abp.AbpBootstrapper.Initialize() in AbpBootstrapper.cs
Abp.AspNetCore.AbpApplicationBuilderExtensions.InitializeAbp(IApplicationBuilder app) in AbpApplicationBuilderExtensions.cs
Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action<AbpApplicationBuilderOptions> optionsAction) in AbpApplicationBuilderExtensions.cs
VVV.Web.Host.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+
            app.UseAbp(options => { options.UseAbpRequestLocalization = false; }); // Initializes ABP framework.
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by staneee** [comment]
数据库出错了吧,重新迁移创建
