### ISSUE TITLE
为啥无法启动

### ISSUE THREAD

**Issue by xiangxingze** [52ABP/LTMCompanyNameFree.YoyoCmsTemplate#2]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3491	未能向文件“obj\Debug\netcoreapp2.1\LTMCompanyNameFree.YoyoCmsTemplate.Core.csproj.CoreCompileInputs.cache”写入命令行。指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。	LTMCompanyNameFree.YoyoCmsTemplate.Core	D:\Program Files (x86)\Microsoft Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	3426

**Comment by ltm0203** [comment]
放到根目录去。路径太长了。
