### ISSUE TITLE
前端无法启动

### ISSUE THREAD

**Issue by xiangxingze** [52ABP/LTMCompanyNameFree.YoyoCmsTemplate#3]
npm install
npm WARN @delon/abc@1.3.1 requires a peer of qrious@^4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

ngular-zorro-free> ng server
Your global Angular CLI version (6.1.3) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The specified command ("server") is invalid. For a list of available options,
run "ng help".

Did you mean "serve"?

**Comment by ltm0203** [comment]
前端已经重新生成。
建议使用  yarn  进行包的还原。
