### ISSUE TITLE
'TitleOrCallBack' always undefined

### ISSUE THREAD

**Issue by rqx110** [52ABP/LTMCompanyNameFree.YoyoCmsTemplate#8]
https://github.com/52ABP/LTMCompanyNameFree.YoyoCmsTemplate/blob/68da5827905991e35adccdaa21d9bfd94b9488f5/src/angular-zorro-free/src/shared/AppConsts.ts#L188

https://github.com/52ABP/LTMCompanyNameFree.YoyoCmsTemplate/blob/68da5827905991e35adccdaa21d9bfd94b9488f5/src/angular-zorro-free/src/shared/AppConsts.ts#L191

The `TitleOrCallBack` is always `undefined`.

**Comment by ltm0203** [comment]
@staneee 空的时候，帮忙看看这个问题能否解决。

**Comment by staneee** [comment]
Please upgrade yoyo-ng-module to version 1.1.35
